server:
  port: 8082
logging:
  level: debug

spring:
  thymeleaf:
      check-template-location: true
      content-type: text/html
      enabled: true
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
      template-resolver-order:

